In [ ]:
# ============================
# Random Forest on Iris
# ============================

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#  Load dataset
#https://github.com/scikit-learn/scikit-learn/blob/98ed9dc73a86f5f11781a0e21f24c8f47979ec67/sklearn/datasets/data/iris.csv
#https://archive.ics.uci.edu/dataset/53/iris
iris = load_iris()
X = iris.data
y = iris.target

#  Train/Test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Train Random Forest
rf = RandomForestClassifier(
    n_estimators=100   # number of trees
    random_state=42
)

rf.fit(X_train, y_train)

# Predictions
y_pred = rf.predict(X_test)

# Evaluation
print("Train accuracy:", rf.score(X_train, y_train))
print("Test accuracy :", accuracy_score(y_test, y_pred))

print("\nConfusion matrix:\n", confusion_matrix(y_test, y_pred))

print("\nClassification report:\n")
print(classification_report(y_test, y_pred, target_names=iris.target_names))


Train accuracy: 1.0
Test accuracy : 0.9

Confusion matrix:
 [[10  0  0]
 [ 0  9  1]
 [ 0  2  8]]

Classification report:

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.82      0.90      0.86        10
   virginica       0.89      0.80      0.84        10

    accuracy                           0.90        30
   macro avg       0.90      0.90      0.90        30
weighted avg       0.90      0.90      0.90        30



In [ ]:
print(X.shape)

(150, 4)


In [ ]:
from sklearn.model_selection import cross_val_score
import numpy as np

scores = cross_val_score(rf, X, y, cv=5)

print("CV accuracy per fold:", scores)
print("Mean CV accuracy:", np.mean(scores))


CV accuracy per fold: [0.96666667 0.96666667 0.93333333 0.96666667 1.        ]
Mean CV accuracy: 0.9666666666666668


In [ ]:
# =========================================
# Compare Decision Tree vs Random Forest
# (side-by-side on Iris)
# =========================================

import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# 1) Load data
iris = load_iris()
X = iris.data
y = iris.target

# 2) Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 3) Models
dt = DecisionTreeClassifier(random_state=42)
rf = RandomForestClassifier(n_estimators=10, random_state=42)

models = {
    "Decision Tree": dt,
    "Random Forest": rf
}

# 4) Train + evaluate (Train/Test + CV)
print(f"{'Model':<15} | {'Train Acc':>9} | {'Test Acc':>8} | {'CV Mean':>7} | {'CV Std':>6}")
print("-"*60)

for name, model in models.items():
    model.fit(X_train, y_train)

    train_acc = model.score(X_train, y_train)
    test_acc = accuracy_score(y_test, model.predict(X_test))

    cv_scores = cross_val_score(model, X, y, cv=5)  # CV on full dataset
    cv_mean = cv_scores.mean()
    cv_std = cv_scores.std()

    print(f"{name:<15} | {train_acc:9.3f} | {test_acc:8.3f} | {cv_mean:7.3f} | {cv_std:6.3f}")


Model           | Train Acc | Test Acc | CV Mean | CV Std
------------------------------------------------------------
Decision Tree   |     1.000 |    0.933 |   0.953 |  0.034
Random Forest   |     1.000 |    0.967 |   0.967 |  0.021
