# One-Hot Encoding

One-hot encode labels: 0 -> [1,0], 1 -> [0,1]

y_train = to_categorical(y_train, 2)

y_test  = to_categorical(y_test, 2)



Predict probabilities for 2 classes

y_prob = model.predict(X_test)           # shape: (N, 2)

[0.42362958 0.468102  ]


y_pred = np.argmax(y_prob, axis=1)       # shape: (N,)






In [ ]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

# Load dataset
data = load_breast_cancer()
X = data.data
y = data.target  # 0/1

# Train/Test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Scale
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

# One-hot encode labels: 0 -> [1,0], 1 -> [0,1]
y_train_cat = to_categorical(y_train, num_classes=2)
y_test_cat  = to_categorical(y_test, num_classes=2)

# Model: 2 outputs + sigmoid
model = Sequential([
    Dense(16, activation='relu', input_shape=(30,)),
    Dense(16, activation='relu'),
    Dense(2, activation='sigmoid')
])

model.compile(
    optimizer='sgd',
    loss='mse',
    metrics=['accuracy']
)



# Train
history = model.fit(
    X_train, y_train_cat,
    epochs=50,
    batch_size=32,
    validation_split=0.2,
    verbose=0
)

# Predict probabilities for 2 classes
y_prob = model.predict(X_test)           # shape: (N, 2)

y_prob

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


array([[0.2962096 , 0.65788597],
       [0.8945156 , 0.28114015],
       [0.6714307 , 0.372016  ],
       [0.23823324, 0.69870925],
       [0.30463758, 0.67311734],
       [0.9878195 , 0.03858046],
       [0.9878734 , 0.0722097 ],
       [0.7216618 , 0.36559764],
       [0.4728651 , 0.35007092],
       [0.2125926 , 0.8666112 ],
       [0.19257787, 0.8803992 ],
       [0.57392114, 0.43749103],
       [0.19569427, 0.8780119 ],
       [0.6273272 , 0.33860084],
       [0.08057257, 0.88398933],
       [0.8760749 , 0.14491528],
       [0.20082033, 0.84933007],
       [0.06713901, 0.9207904 ],
       [0.00805947, 0.9719056 ],
       [0.91869795, 0.15846898],
       [0.36777198, 0.63804466],
       [0.15590462, 0.8184619 ],
       [0.9622772 , 0.06725789],
       [0.04067682, 0.95439696],
       [0.17399527, 0.88683987],
       [0.1386939 , 0.9056485 ],
       [0.20126899, 0.80331475],
       [0.2217328 , 0.7938173 ],
       [0.14511968, 0.8669187 ],
       [0.9743208 , 0.12215405],
       [0.

In [ ]:
y_prob = model.predict(X_test[:1])
y_prob

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step


array([[0.29620957, 0.6578859 ]], dtype=float32)

In [ ]:
# Convert to predicted class (0 or 1)
y_pred = np.argmax(y_prob, axis=1)       # shape: (N,)
y_pred

array([1])

# Binary Classification with Single Output Neuron

In [ ]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Load dataset
data = load_breast_cancer()
X = data.data
y = data.target

print("Shape:", X.shape)
print("Classes:", set(y))

# Train / Test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Normalize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)



# Model
model = Sequential([
    Dense(16, activation='relu', input_shape=(30,)),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='sgd',
    loss='mse',
    metrics=['accuracy']
)



# Train
history = model.fit(
    X_train, y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.2,
    verbose=0
)

# Predict probabilities
y_prob = model.predict(X_test[:1])
y_prob


Shape: (569, 30)
Classes: {np.int64(0), np.int64(1)}


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step


array([[0.6865127]], dtype=float32)

In [ ]:

# Convert probabilities to class labels
y_pred = (y_prob > 0.5).astype(int)

y_pred

array([[1]])

# Binary Classification with Binary Cross-Entropy Loss

compile -> loss --> with binary_crossentropy
https://www.tensorflow.org/api_docs/python/tf/keras/losses


In [ ]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Load dataset
data = load_breast_cancer()
X = data.data
y = data.target

print("Shape:", X.shape)
print("Classes:", set(y))

# Train / Test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Normalize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)



# Model
model = Sequential([
    Dense(16, activation='relu', input_shape=(30,)),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='sgd',
    loss='binary_crossentropy',  #loss='mse'
    metrics=['accuracy']
)



# Train
history = model.fit(
    X_train, y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.2,
    verbose=0
)

# Predict probabilities
y_prob = model.predict(X_test[:1])
y_prob


Shape: (569, 30)
Classes: {np.int64(0), np.int64(1)}


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step


array([[0.83326274]], dtype=float32)

TensorFlow docs: https://www.tensorflow.org/api_docs/python/tf
